---
title: "clustering"
output: html_notebook
---


K MEDOIDS  -- clustering the streamers into 4 tiers(S,A,B,C) based on attributes

```{r}
df=read.csv("D:/vit/sem5/fda/jcomp/twitchdata final.csv",header=T)
library(factoextra)
library(cluster)
library(dplyr)
```

choosing the attributes for finding cluster
```{r}
df2=select(df,c(Channel,Watch.time.Minutes.,Followers,Followers.gained,Average.viewers,Partnered,Language,Views.gained))
lang=factor(df2$Language)
df2$Language=as.numeric(factor(df2$Language))
partner=factor(df2$Partnered)
df2$Partnered=as.numeric(factor(df2$Partnered))
dfk=scale(df2[,2:8])
head(dfk)
```
finding appropriate number of clusters required
```{r}
fviz_nbclust(dfk, pam, method = "wss")

```


performing kmedoids to cluster streamers into different tiers and plotting the clusters using first 2 principal components

```{r}
kmed=pam(dfk,k=6)
fviz_cluster(kmed,data=dfk)

```

```{r}
channel.Tier=kmed[3]
df2=read.csv("D:/vit/sem5/fda/jcomp/twitchdata final.csv")
dfcluster=data.frame(df,channel.Tier)
dfcluster=rename(dfcluster,channel.Tier=clustering)
dfcluster=arrange(dfcluster,channel.Tier)
dfcluster$channel.Tier=factor(dfcluster$channel.Tier)
label=c("S","A","B","C","D","E")
levels(dfcluster$channel.Tier)=label
dfcluster$Language=factor(dfcluster$Language)
dfcluster$Language=df2$Language
levels(dfcluster$Language)=levels(lang)
levels(dfcluster$Partnered)=levels(partner)
head(dfcluster)
tiercount=table(channel.Tier)
tiercount
```
```{r}
barplot(tiercount,names.arg=label,main="number of channels in each tier")

```
```{r}
stier=filter(dfcluster,channel.Tier=="S")
atier=filter(dfcluster,channel.Tier=="A")
btier=filter(dfcluster,channel.Tier=="B")
ctier=filter(dfcluster,channel.Tier=="C")
dtier=filter(dfcluster,channel.Tier=="D")
etier=filter(dfcluster,channel.Tier=="E")
summary(stier)
summary(atier)
summary(btier)
summary(ctier)
summary(dtier)
summary(etier)
```

```{r}
write.csv(dfcluster,"D:/vit/sem5/fda/jcomp/twitchdata_eda.csv")
```



HEIRARCHICAL CLUSTERING
```{r}
df=read.csv("D:/vit/sem5/fda/jcomp/twitchdata_eda.csv")
head(df[,1:8])
df1 <- df[c("Peak.viewers","Followers","Followers.gained","Views.gained")]
distance_mat <- dist(df1, method = 'euclidean')

set.seed(240)  # Setting seed
Hierar_cl <- hclust(distance_mat, method = "average")
Hierar_cl

```
Plotting dendrogram
```{r}

plot(Hierar_cl)
fit <- cutree(Hierar_cl, k = 3 )
table(fit)
rect.hclust(Hierar_cl, k = 3, border = "red")

```
```{r}
df=dplyr::mutate(df,clusters=fit)
df$clusters=as.factor(df$clusters)
levels(df$clusters)
label=c("S","A","B")
levels(df$clusters)=label
table(df$clusters)

```

```{r}
streamerS=dplyr::filter(df,clusters=="S")
streamerA=dplyr::filter(df,clusters=="A")
streamerB=dplyr::filter(df,clusters=="B")
summary(streamerS)
summary(streamerA)
summary(streamerB)
```
```{r}

barplot(table(df$clusters),main="streamer tiers")
```

